spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yeetcode
    username: yeetcode
    password: example
  jpa:
    generate-ddl: true
    show-swl: true
    hibernate:
      ddl-auto: update
      hbm2ddl:
        auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org:
      springframework:
        security: TRACE

frontend:
  url: "http://localhost:5173"